// <auto-generated />
namespace RCP.DL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class version23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(version23));
        
        string IMigrationMetadata.Id
        {
            get { return "201912151230111_version2.3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
